# Core Konquest Settings
#    (*) means the server must be restarted for a change to take effect, else use the "/k admin reload" command. NEVER USE /reload.
#    [LEGACY] means a setting is not used in the current version, but still exists to support backwards compatability with previous Konquest versions.
#    Lines that begin with "#" (the entire top-half of this file) are comments and do not control any settings.
# 
# language*:                        Language file selection, must match a file name in the /lang folder (e.g. english for lang/english.yml)
# core:
#  debug*:                          Enable debug messages for verbose console messages (true/false)
#  world_name*:                     [LEGACY] Primary world name for kingdoms and towns created before v0.3.0 (string)
#  world_blacklist*:                World names where kingdoms and towns cannot exist (string list)
#  world_blacklist_reverse*:        Reverse world_blacklist into a whitelist, where listed world names become the only worlds where kingdoms and towns can exist (true/false)
#  save_interval*:                  Save interval in minutes, 0 to disable (integer >= 0)
#  community_link:                  URL which will appear in the /k community link icon (string)
#  accomplishment_prefix:           Enable the usage of accomplishment prefixes applied to player names (true/false)
#  directive_quests:                Enable the "/k quest" command and built-in quest rewards (true/false)
#  travel_wild_random_radius:       Radius in blocks from the center of the primary world for random wild travel (integer > 0)
# chat:
#     tag*:                         Text tag for all Konquest plugin messages. Use '' to disable. Use & for color codes. ('string')
#     enable_format:                Enable Konquest formatting chat messages, which overrides all other plugin chat formatting (true/false)
#     use_kingdom:                  Use a player's kingdom name as a part of their chat message (true/false)
#     priority:                     Set the priority of Konquest's chat message formatting. Set to low to allow other plugins to modify chat first (lowest, low, normal, high, highest)
#  database:
#      connection:                  Database connection type (sqlite or mysql)
#      mysql:
#        hostname:                  MySQL database hostname
#        port:                      MySQL database port number
#        database:                  MySQL database name
#        username:                  MySQL database username
#        password:                  MySQL database password
#        properties:                MySQL connection properties as a string list (e.g. ["autoReconnect=true","useSSL=false"])
#  integration:
#    quickshop*:                    Enable plugin integration with QuickShop (true/false)
#    luckperms*:                    Enable plugin integration with LuckPerms (true/false)
#    dynmap*:                       Enable plugin integration with Dynmap (true/false)
#  kingdoms:
#    capital_suffix*:               Suffix to be appended to Kingdom names which will be the name of the Capital city (string)
#    capital_pvp:                   Allow player damage in capitals (true/false)
#    capital_use:                   Allow players to interact with blocks and containers in capitals (true/false)
#    protect_containers_use:        Prevent players in other kingdoms using containers in claimed land (true/false)
#    protect_containers_break:      Prevent players in other kingdoms breaking containers in claimed land (true/false)
#    no_enemy_enter:                Prevent enemy players from entering Kingdom Capitals (true/false)
#    no_enemy_travel:               Prevent enemy players from traveling within Kingdom territory (true/false)
#    no_enemy_edit_offline:         Prevent enemy players from breaking any blocks in a Kingdom with no players online (true/false)
#    no_enemy_edit_offline_warmup:  Time in seconds when a Kingdom is protected from when the minimum player disconnects (integer >= 0)
#    no_enemy_edit_offline_minimum: Number of players required for a Kingdom to be protected (integer >= 0)
#    smallest_exp_boost_percent:    Percentage boost EXP gain for the smallest kingdom (0 to disable, 0 - 100)
#    offline_timeout_days:          Time in days a player must be offline to be removed from their Kingdom (0 to disable, integer >= 0)
#    golem_attack_enemies:          Force iron golems to attack enemy players (true/false)
#    attack_friendly_golems:        Allow players to attack iron golems inside of friendly towns (true/false)
#    max_player_diff:               Kingdoms with this many players more than other Kingdoms will not accept new players (0 to disable, integer >= 0)
#    allow_exile_switch:            Allow barbarians to join any kingdom, even when exiled (true) or prevent exiled barbarians from switching kingdoms (false) (true/false)
#    per_kingdom_join_permissions:  When true, players must have a permission "konquest.join.<kingdom>" to join specific kingdoms, e.g. "konquest.join.rome" to join the kingdom Rome (true/false)
#  towns:
#    min_settle_height:             Minimum height level for new town settlements (0 to disable, 0 - 256)
#    max_settle_height:             Maximum height level for new town settlements (0 to disable, 0 - 256), Note, if max_settle_height is less than min_settle_height, things might break!
#    min_distance_town:             Minimum distance in chunks between Towns and other Towns (integer >= 0)
#    min_distance_capital:          Minimum distance in chunks between Towns and Capitals (integer >= 0)
#    max_distance_all:              Maximum distance in chunks between Towns and all other territory (0 to disable, integer >= 0)
#    init_radius:                   Radius of initial settlements. Initial chunk area will be (2r-1)^2 chunks squared (integer >= 0)
#    capture_cooldown:              Time in seconds before a town can be captured again (integer >= 0)
#    raid_alert_cooldown:           Time in seconds between raid alerts for Towns (integer >= 0)
#    travel_cooldown:               Time in seconds for travel cool-down (integer >= 0)
#    enable_upgrades:               Enable town upgrades and the upgrade GUI menu (true/false)
#    enable_shields:                Enable town shields, which prevent all enemy attacks, in the shield GUI menu (true/false)
#    enable_armor:                  Enable town armor, which prevents a limited number of enemy block edits, in the shield GUI menu (true/false)
#    shields_while_attacked:        Allow shields to be charged charged while a town is under attack (true/false)
#    armor_while_attacked:          Allow armor to be applied while a town is under attack (true/false)
#    shields_add:                   Allow new shields to add onto existing shields when true, else require shields to deplete before charging again (true/false)
#    armor_add:                     Allow new armor to add onto existing armor when true, else require armor to deplete before applying again (true/false)
#    max_shields:                   Maximum shield duration in seconds that a town can have (0 to disable, integer >= 0)
#    max_armor:                     Maximum armor amount in blocks that a town can have (0 to disable, integer >= 0)
#  exile:
#    remove_favor:                  Set a player's currency balance to 0 when exiled (true/flase)
#    remove_stats:                  Remove all stats and accomplishment prefixes from a player when exiled (true/false)
#  camps:
#    init_radius:                   Radius of camps for barbarians. Initial chunk area will be (2r-1)^2 chunks squared (integer >= 0)
#  monuments:
#    critical_block*:               Blocks which must be destroyed to capture a town monument (Material, https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html, e.g. for obsidian, enum is OBSIDIAN)
#    destroy_amount:                Amount of each destroy_blocks that must be destroyed to capture a town monument (integer >= 0)
#    damage_regen:                  The time in seconds it takes a damaged monument to regenerate after being attacked (integer >= 0)
#    loot_refresh:                  Time in seconds between monument loot refresh (integer >= 0)
#    loot_count:                    Number of loot items to appear in monument loot chests (integer >= 0)
#  ruins:
#    critical_block*:               Blocks which must be destroyed to capture a ruin (Material, https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html, e.g. for obsidian, enum is OBSIDIAN)
#    capture_cooldown:              Time in seconds between ruin captures (integer >= 0)
#    respawn_cooldown:              Time in seconds for ruin golems to respawn (integer >= 0)
#    capture_reward_favor:          Amount of Favor rewarded to players upon ruin capture (integer >= 0)
#    capture_reward_exp:            Amount of experience rewarded to players upon ruin capture (integer >= 0)
#  favor:
#    cost_spy:                      Cost to use the spy command (decimal >= 0)
#    cost_settle:                   Cost to settle a new Town (decimal >= 0)
#    cost_settle_increment:         Additional cost for each town settled (decimal >= 0)
#    cost_rename:                   Cost to rename a Town (decimal >= 0)
#    cost_claim:                    Cost to claim land (decimal >= 0)
#    cost_travel:                   Cost to travel (decimal >= 0)
#    cost_travel_per_chunk:         Additional cost to travel per-chunk (decimal >= 0)
#    cost_travel_world:             Cost to travel between worlds (decimal >= 0)
#    allow_travel_always:           Allow players to travel even when they can't pay the cost (true/false)
#    rewards:
#      settle_town:                 Quest reward for settling a town, requires konquest.directive.settle permission (integer >= 0)
#      claim_land:                  Quest reward for claiming land, requires konquest.directive.claim permission (integer >= 0)
#      build_town:                  Quest reward for building in a town, requires konquest.directive.build permission (integer >= 0)
#      create_golem:                Quest reward for creating an iron golem in a friendly town, requires konquest.directive.golem permission (integer >= 0)
#      craft_armor:                 Quest reward for crafting iron armor, requires konquest.directive.armor permission (integer >= 0)
#      enchant_item:                Quest reward for enchanting an item, requires konquest.directive.enchant permission (integer >= 0)
#      attack_town:                 Quest reward for attacking an enemy town, requires konquest.directive.attack permission (integer >= 0)
#      capture_town:                Quest reward for capturing an enemy town, requires konquest.directive.capture permission (integer >= 0)
#      kill_enemy:                  Quest reward for killing an enemy, requires konquest.directive.kill permission (integer >= 0)
#      defend_raid:                 Reward for defending a town from attack, does not require any permission (integer >= 0)
#  combat:
#    prevent_command_on_proximity:  Enable combat tagging when enemies are in close priximity (true/false) (NOT CURRENTLY IMPLEMENTED)
#    prevent_command_on_damage:     Enable combat tagging when damaged by an enemy (true/false)
#    enemy_proximity_chunks:        Distance in chunks for proximity combat tag (integer >= 0) (NOT CURRENTLY IMPLEMENTED)
#    enemy_damage_cooldown_seconds: Time in seconds for combat tag cooldown (integer >= 0)
#    prevent_command_list:          List of commands to prevent while combat tagged, each command belongs on its own line, e.g. - home (string list)
# 
# /!\ DO NOT MODIFY VERSION /!\
version: 0.0.0
language: english
core:
  debug: false
  world_name: world
  world_blacklist:
  - world_nether
  - world_the_end
  world_blacklist_reverse: false
  save_interval: 60
  community_link: www.google.com
  accomplishment_prefix: true
  directive_quests: true
  travel_wild_random_radius: 1000
  chat:
    tag: '&7[&6Konquest&7]&f '
    enable_format: true
    use_kingdom: true
    priority: low
  database:
    connection: sqlite
    mysql:
      hostname: localhost
      port: 3306
      database: example_database
      username: example_user
      password: example_password
      properties: []
  integration:
    quickshop: false
    luckperms: false
    dynmap: false
  kingdoms:
    capital_suffix: Capital
    capital_pvp: false
    capital_use: false
    protect_containers_use: true
    protect_containers_break: true
    no_enemy_enter: true
    no_enemy_travel: true
    no_enemy_edit_offline: true
    no_enemy_edit_offline_warmup: 300
    no_enemy_edit_offline_minimum: 2
    smallest_exp_boost_percent: 25
    offline_timeout_days: 0
    golem_attack_enemies: true
    attack_friendly_golems: false
    max_player_diff: 4
    allow_exile_switch: true
    per_kingdom_join_permissions: false
  towns:
    min_settle_height: 2
    max_settle_height: 200
    min_distance_town: 16
    min_distance_capital: 16
    max_distance_all: 99
    init_radius: 2
    capture_cooldown: 600
    raid_alert_cooldown: 30
    travel_cooldown: 120
    enable_upgrades: true
    enable_armor: true
    enable_shields: true
    armor_tnt_damage: 10
    shields_while_attacked: false
    armor_while_attacked: false
    shields_add: true
    armor_add: true
    max_shields: 432000
    max_armor: 9999
  exile:
    remove_favor: true
    remove_stats: true
  camps:
    init_radius: 2
  monuments:
    critical_block: OBSIDIAN
    destroy_amount: 12
    damage_regen: 300
    loot_refresh: 1200
    loot_count: 1
  ruins:
    critical_block: OBSIDIAN
    capture_cooldown: 3600
    respawn_cooldown: 60
    capture_reward_favor: 100
    capture_reward_exp: 1000
  favor:
    cost_spy: 200
    cost_settle: 100
    cost_settle_increment: 50
    cost_rename: 50
    cost_claim: 10
    cost_travel: 1
    cost_travel_per_chunk: 0.01
    cost_travel_world: 5
    allow_travel_always: true
    rewards:
      settle_town: 50
      claim_land: 50
      build_town: 100
      create_golem: 25
      craft_armor: 25
      enchant_item: 25
      attack_town: 100
      capture_town: 100
      kill_enemy: 50
      defend_raid: 50
  combat:
    prevent_command_on_proximity: false
    prevent_command_on_damage: true
    enemy_proximity_chunks: 3
    enemy_damage_cooldown_seconds: 30
    prevent_command_list:
    - k travel
    - k settle
    - k exile
    - k claim
